packages:
  - apps/*
  - packages/*
  - tests

allowBuilds:
  esbuild: true
  msgpackr-extract: false
  sharp: true
  unrs-resolver: false

overrides:
  postcss: 8.5.16

catalog:
  '@types/node': 24.10.1
  typescript: 5.9.3
  yaml: 2.9.0

minimumReleaseAgeExclude:
  - bullmq@5.80.1
